/*
 * PRINT_DECODE_BATTERY_MANAGEMENT_SYSTEM.h
 *
 *  Created on: Aug 10, 2026
 *      Author: MadaYaswanth
 */

#ifndef INC_PRINT_DECODE_BATTERY_MANAGEMENT_SYSTEM_H_
#define INC_PRINT_DECODE_BATTERY_MANAGEMENT_SYSTEM_H_



#endif /* INC_PRINT_DECODE_BATTERY_MANAGEMENT_SYSTEM_H_ */
